import Header from "@/components/Header";
import "./globals.scss";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import ReduxCustomProvider from "@/redux/ReduxCustomProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxCustomProvider>
        <body className={inter.className} suppressHydrationWarning={true}>
          <Header />
          {children}
          <Footer />
        </body>
      </ReduxCustomProvider>
    </html>
  );
}
